config/routes.rb
PictureFinder::Application.routes.draw do
  match "find" => 'find#create', :method => 'post'
  root :to => 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/find_controller.rb
class FindController < ApplicationController
  def create
    query = params[:query]
    search_uri = "http://api.search.live.net/xml.aspx"
    r = RestClient.get(search_uri,
                       :params => {
                         :query => query,
                         :sources => 'image',
                         "Image.Filters" => 'Size:Medium',
                         :Appid => 'C3153D6EC8CD21E7BC784BD3087A3B415C352027'})
    n = Nokogiri(r).remove_namespaces!
    results = n.css('MediaUrl')
    if results.present?
      image = results[rand(results.length)].content
      flash[:notice] = "Found one!"
      redirect_to root_path(:image => Base64.encode64(image), :query => query)
    else
      flash[:notice] = "Sorry, nothing found"
      redirect_to root_path(:query => query)
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Picture Finder!
    = stylesheet_link_tag "application"
    = csrf_meta_tags

  %body.finder

    %h1 Find A Picture

    - if flash[:notice]
      .notice= flash[:notice]

    = yield

    #about
      Brought to you by #{ mail_to "joe@tanga.com", "Joe" }.
      &copy; #{ Time.now.year }
    = javascript_include_tag "application"

app/views/welcome/index.html.haml
= form_tag find_path do
  = text_field_tag :query, params[:query], :class => 'focus'
  = submit_tag "Go!"

- if params[:image]
  #result= image_tag Base64.decode64(params[:image])